name             'gem_fix'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures gem_fix'
long_description 'Installs/Configures gem_fix'
version          '0.1.0'
