name             'pg_gem_fix'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures pg_gem_fix'
long_description 'Installs/Configures pg_gem_fix'
version          '0.1.0'
